TEST to look at Gh build vs tip
PCGen/pcgen pull request #7247
Opened 2024-12-24 04:12 UTC by karianna

2024-12-24 08:13 UTC, Vest commented
Please wait (as usual, I cannot tell until when) and don't merge this PR

2024-12-27 23:09 UTC, karianna commented
Yeah I assume we won't merge this PR, I figured it was just the easierst way to look at a diff and see if we could spot anything.

2025-01-07 23:09 UTC, karianna commented
Super interesting those tests fail for you but not for me locally!

2025-01-11 06:46 UTC, karianna commented
> If you use your version/branch, but not mine, I bet you have this PR: #6975 It comments the most important part, when the character sheet is exported. I have uncommented it, and now the tests started failing. (mostly because LegacyKing corrected some data-files).

OK, so just a data fix required then?

2025-01-11 11:53 UTC, Vest commented
Not only:
1. DATA changes caused slowtests to fail
2. Some XML files were not trimmed
3. The template was trimmed (no leading whitespaces)
4. That's all. I am waiting for the next build :smile:

2025-01-11 16:53 UTC, Vest commented
Two commits above this comment are related to #7079. Security manager is mostly used to intercept System.exit calls;
I have created required classes to replace System.exit with my proposed class. 

I hope, you will like it.

2025-01-11 22:33 UTC, karianna commented
Looks like it all passed!  Shall we take out of Draft?

2025-01-11 22:51 UTC, Vest commented
It is unfinished. Do you insist? I need:
1. remove security manager
2. replace all System.exit calls 
3. I have disabled NSIS, but I have not moved to jpackage a windows build yet. 

If you don’t need release builds for windows for now. I would implement my PR simply to have indicators that tests are green. 

Are you sure? Because I am not. 

You can actually merge it, but I only if you plan to work with the new codebase. E.g., continue improving GH actions. If not, I would keep it for a while draft.

2025-01-13 09:59 UTC, Vest commented
The commit 59833c5 addresses the issue #7079. We don't use SecurityManager directly (maybe its exceptions are still thrown here and there), but I have created a custom interceptor, called pcgen.util.ExitInterceptor. It is used in several test-classes.
@karianna, if you want, you can link this PR to the mentioned issue #7079 
@Azhrei, I know, you were assigned to this issue. Since I haven't heard any news from you, I think, you were busy with your life. If you are curious about my implementation, can you please review this PR? Not entirely, but you can look at the class: GracefulExit, ExitInterceptor, ExitFunction and few tests that I modified.

I don't know, if I should move my three "exit"-related classes/interfaces into a nested package (just to reduce litter in utils package). If you think, it will be a good idea, I will do this. Something like: "pcgen.util.exit".

Thank you all.

2025-01-13 10:01 UTC, Vest commented
<img alt="Code coverage of CommandLineArgs" src="https://github.com/user-attachments/assets/1f2eaca3-3109-45d0-be4b-1678ad2e6a80" />

<img alt="Code coverage of GracefulTest" src="https://github.com/user-attachments/assets/4aedf5a0-e620-4364-a168-16af1a3b9fcd" />

2025-01-13 14:59 UTC, Azhrei commented
Thanks.  I actually have some time today, so yes, I'll take a look.  It'll be a couple hours from now, most likely.

Since intercepting System.exit() is a no-no, I'm very curious to see how you did it!

2025-01-13 15:02 UTC, Vest commented
I don’t intercept it. I have got rid of it. There is only one place, where I allow it - GracefulExit :smile:
The rest is filtered out with CheckStyle. If you accidentally write System.exit, it won’t pass CheckStyle (a simple regexp within all sources - dumb, but solid). You can bypass it, if you overcome my regexp (e.g., use reflection + build the string at runtime). 
thanks.

2025-01-13 23:21 UTC, karianna commented
@Vest Will happily wait until you're done, thanks for tackling this!

2025-01-14 00:30 UTC, Azhrei requested changes
Wow, big changeset. 🙂  A lot changes not directly related to `GracefulExit`, but I mostly skimmed those.

I like the idea of using GE as a front-end on `System.exit()`.

It all looks good to me!

2025-01-14 00:30 UTC, Azhrei commented on code/src/java/pcgen/persistence/lst/LstFileLoader.java
>  							"The file %s uses UTF-8-BOM encoding. LST files must be UTF-8".formatted(uri));
Error message should be in a properties file...
Also, at a higher level, a file that starts with a UTF-8-BOM actually *is* a UTF-8 file, so this whole area might need reworking.

2025-01-14 00:30 UTC, Azhrei commented on code/src/java/pcgen/persistence/lst/LstFileLoader.java
> +								+ "sources from web links.\n" + uri + " is a web link", Constants.APPLICATION_NAME,
Another properties file template string...?

2025-01-14 08:29 UTC, Vest commented on code/src/java/pcgen/core/PlayerCharacter.java
> +			case MEDIUM -> 3;
Nice catch, but no :) I have found this bug, when my integration tests failed:

<img alt="Encumbrance Effects" src="https://github.com/user-attachments/assets/73c820d4-581a-4493-9a14-f673f7c4e13e" />

Max Dex must be +3

2025-01-14 11:06 UTC, Vest commented on code/src/java/pcgen/persistence/lst/LstFileLoader.java
> +								+ "sources from web links.\n" + uri + " is a web link", Constants.APPLICATION_NAME,
Done!

2025-01-14 11:13 UTC, Vest commented on code/src/java/pcgen/persistence/lst/LstFileLoader.java
>  							"The file %s uses UTF-8-BOM encoding. LST files must be UTF-8".formatted(uri));
Nope.
I don't honestly know what to deal with the error here. I have explained you that we had Apache Commons something (maybe String commons, I don't remember exactly) to work with BOM-files. I wanted to optimize the build, and I was trying to get rid of dependencies that are not that important.

When I analyzed all LST files, I found out that we had BOM in (maybe) 10 files, not more. It was easier for me to remove BOM and write code that fails/warns the user, if he gives an unsupported file.

LegacyKing was the first one (we don't have many data-contributors), who stepped this mine first. He was disappointed with the error, and I had to write this code just for him.

My thoughts are to add a Gradle task to go through all LST (or DATA) files and scan for BOM. Either convert them to non-BOM, or fail the build or whatever. 

If I don't throw an error, a wrong LST will be pushed to the repo (I don't want this). If I throw an error, probably this build will fail and somebody else will be unhappy. Maybe I should convert LST files silently, but Karianna didn't like when "gradle test" modified .properties files even when nothing was changed. Maybe I'd better write an integration test that will fail, and after this PR is ready we will be able to see in the pull request, who is trying to break the build. Maybe I will also add a task such as "checkLst" to Gradle, so it will convert broken files to good ones. And in the test exception, I will write something like "BOM detected. Test failed. Use gradle checkLst to repair".

2025-01-14 16:32 UTC, Azhrei commented on code/src/java/pcgen/persistence/lst/LstFileLoader.java
>  							"The file %s uses UTF-8-BOM encoding. LST files must be UTF-8".formatted(uri));
Sounds like you've got it under control. I wasn't aware of the backstory. 👍

2025-01-31 16:06 UTC, Vest commented
@karianna please check my PR: https://github.com/Vest/pcgen/pull/1
Do you like it?

2025-02-01 00:38 UTC, karianna commented
> @karianna please check my PR: [Vest#1](https://github.com/Vest/pcgen/pull/1) Do you like it?

Looks great!

2025-02-01 21:45 UTC, Vest commented
Ok, I'd say that we have something, that I can call "release": https://github.com/Vest/pcgen/releases/tag/v0.0.8

**Attention:** I am not a professional devops. So, I am experimenting with my workflow. Really. So, it can build releases now. I have tested a mac release only. The application starts. It isn't signed, but it can run.

My thoughts - delete NSIS completely. But I have to verify windows & linux builds somehow.

@karianna

2025-02-02 22:45 UTC, karianna commented
> Ok, I'd say that we have something, that I can call "release": https://github.com/Vest/pcgen/releases/tag/v0.0.8
> 
> **Attention:** I am not a professional devops. So, I am experimenting with my workflow. Really. So, it can build releases now. I have tested a mac release only. The application starts. It isn't signed, but it can run.
> 
> My thoughts - delete NSIS completely. But I have to verify windows & linux builds somehow.
> 
> @karianna

Is it also possible to create .deb linux distro files?  I can test on an Ubuntu system (although it'll be Arm based), I can also test Windows (Arm) but I suspect the exe file is for x86-64?

2025-02-03 02:58 UTC, Azhrei commented
It is.  GitHub makes a number of environments available for performing the build.  x86_64 is supported for Windows and Linux, and arm64 for Linux and macOS (not sure about Windows).  The Debian (including Ubuntu) and Red Hat (not sure about Fedora) Linux distros are supported.

It's not difficult to create a matrix of supported architectures and supported platforms, then let GitHub build ALL OF THEM!  Obviously, you'd want to be careful about triggering that one!

2025-10-03 14:27 UTC, LegacyKing commented
Where do we stand with this?

2025-10-03 15:16 UTC, Vest commented
I am updating this PR from time to time. But I am stuck at failed tests (sometimes your changes break the tests that were green before), and I am analyzing the results (but not that fast as I wanted), and I am still not certain that all three OSes are 100% working :(
I don’t want to abandon this PR honestly. It should improve the build speed.

2026-02-26 06:53 UTC, closed without merging